set(CPACK_PACKAGE_VENDOR "Daid")
set(CPACK_PACKAGE_CONTACT "Daid <daid303@gmail.com>")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "Rogue - dungeons of dooooom.")
set(CPACK_PACKAGE_VERSION_MAJOR 9999)
set(CPACK_PACKAGE_VERSION_MINOR 99)
set(CPACK_PACKAGE_VERSION_PATCH 99)
set(CPACK_GENERATOR "DEB")

set(CPACK_DEBIAN_PACKAGE_ARCHITECTURE armhf)

include(CPack)
